
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UNameBox = new javax.swing.JTextField();
        PWordBox = new javax.swing.JPasswordField();
        LoginB = new javax.swing.JButton();
        CanselB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel7.setText("image");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("LOGIN FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 0, 350, 58);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("User Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 250, 140, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 153));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 300, 140, 29);

        UNameBox.setBackground(new java.awt.Color(0, 255, 255));
        UNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNameBoxActionPerformed(evt);
            }
        });
        jPanel1.add(UNameBox);
        UNameBox.setBounds(500, 250, 130, 22);

        PWordBox.setBackground(new java.awt.Color(0, 255, 255));
        PWordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PWordBoxActionPerformed(evt);
            }
        });
        jPanel1.add(PWordBox);
        PWordBox.setBounds(500, 310, 130, 22);

        LoginB.setBackground(new java.awt.Color(0, 153, 153));
        LoginB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginB.setText("Login");
        LoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBActionPerformed(evt);
            }
        });
        jPanel1.add(LoginB);
        LoginB.setBounds(250, 460, 110, 25);

        CanselB.setBackground(new java.awt.Color(0, 102, 102));
        CanselB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CanselB.setText("Cansel");
        CanselB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanselBActionPerformed(evt);
            }
        });
        jPanel1.add(CanselB);
        CanselB.setBounds(520, 460, 90, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\Camera Roll\\WhatsApp Image 2024-06-11 at 21.41.26_f4ea124e.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1250, 790);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 810));

        setSize(new java.awt.Dimension(1096, 835));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PWordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PWordBoxActionPerformed
         
    }//GEN-LAST:event_PWordBoxActionPerformed

    private void LoginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBActionPerformed
       
        String UName;
        String PWord;
        UName =UNameBox.getText();
        PWord =PWordBox.getText();
                   
        if(UName.equals("sarada")&& PWord.equals("123")){
                       
        Home m1 = new Home();
         m1.setVisible(true);
         this.dispose();
                   }
        else{
              JOptionPane.showMessageDialog(null,"UserName or Password Incorrect");
               }
    }//GEN-LAST:event_LoginBActionPerformed

    private void CanselBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanselBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CanselBActionPerformed

    private void UNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNameBoxActionPerformed
                   
    }//GEN-LAST:event_UNameBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CanselB;
    private javax.swing.JButton LoginB;
    private javax.swing.JPasswordField PWordBox;
    private javax.swing.JTextField UNameBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
